### ISSUE TITLE
Inaccuracy in Enum

### ISSUE THREAD

**Issue by SimonRalek** [zighelp/zighelp#22]
Says @enumToInt as opposed to @intFromEnum

`Enum's ordinal values start at 0. They can be accessed with the built-in function @enumToInt.

test "enum ordinal value" {
    try expect(@intFromEnum(Value.zero) == 0);
    try expect(@intFromEnum(Value.one) == 1);
    try expect(@intFromEnum(Value.two) == 2);
}`

**Comment by rofrol** [comment]
Thanks
